# This is a basic workflow to help you get started with Actions
name: MMOitem Builder [Submit test]
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: phoenixdevt-releases
    - name: Install depends
      run: mvn install
    - name: Test with Maven
      run: mvn test
    - name: Build with Maven
      run: mvn -V -B clean package --file pom.xml
    - name: Move files
      run: mkdir staging && cp target/*.jar staging
    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: MMOItems-${{ env.RELEASE_VERSION }}-${{ env.SHORT_SHA }}
    #     path: staging/*.jar
